version: "3"
services:
  back:
    working_dir: /app
    image: webdevops/php-apache-dev:8.1
    container_name: back-prova
    depends_on:
      - mysql
    ports:
      - "8000:80"
    volumes:
      - ".:/app"
    env_file: .env
    restart: always
    environment:
      WAIT_HOSTS: mysql:3306
  mysql:
    image: mysql:5.7.16
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - "./volumes/mysql:/volume/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: senha2077
      MYSQL_DATABASE: prova_cbm
